### ISSUE TITLE
Working directory not same as Dockerfile

### ISSUE THREAD

**Issue by clockworksoul** [JoTrdl/grunt-dock#13]
Hi,

I have a simple, 3-line Dockerfile.  The last line is a simple "COPY" command that takes the "dist" directory and drops it into the image container's /usr/share/nginx/html directory.  However, when I execute this file I get the following output and error:

```
Building image [foo]
Step 1 : FROM nginx
 ---> b4c1ea3cfac2
Step 2 : MAINTAINER Matt Titmus
 ---> Using cache
 ---> 16548937824d
Step 3 : COPY dist /usr/share/nginx/html
Warning: lstat dist: no such file or directory Use --force to continue.
```

The dist directory definitely exists. :)

Is there a way to define the working directory for the purposes of the docker build? Alternatively, can the plugin define it by default as the directory that the Dockerfile lives in?

**Comment by clockworksoul** [comment]
The fault was mine for not reading well enough.  The fix was as simple as passing the directory for the dockerfile argument.

For anybody else with this issue, this:

```
images: {
                    'foo': {// Name to use for Docker
                        dockerfile: './Dockerfile',
                        options: {
                            build: { /* extra options to docker build   */},
                        }
                    }
                }
```

Simply became:

```
images: {
                    'foo': {// Name to use for Docker
                        dockerfile: '.',
                        options: {
                            build: { /* extra options to docker build   */},
                        }
                    }
                }
```

**Comment by JoTrdl** [comment]
Indeed, the config supports single 'Dockerfile' file, directory and direct archive file.
Thanks.

**Comment by cleankod** [comment]
I'd recommend adding a `.dockerignore` file to the root directory to avoid copying whole project to the Docker build context and thus speed up the build:

```
# Ignore all in Docker build context:
**/*

# ... except these:
!dist
```

It will ignore all the directories/files except `dist/`.
