### ISSUE TITLE
Run and Push/Pull commands

### ISSUE THREAD

**Issue by alexandrusavin** [JoTrdl/grunt-dock#4]
It would be useful to also have Run (for watch like tasks) and Push/Pull commands. Push/Pull would be useful for deployment tasks (or? etc...).

If I have some time I can create some pull requests for this tasks.

**Comment by JoTrdl** [comment]
Yes, it will be great. I don't have a lot of time now to work on it!
Dockerode supports these options: https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode

**Comment by lmorandini** [comment]
I have just added a pull request for "push", and I am keen on adding a pull request for "pull" (sorry for the pun), but I would add the options of pull executed by multiple dockers daemon (like it happens on a cluster). 
Tentatively, I was thinking of adding an array of IP addresses (assuming port and auth are the same across all the nodes in the cluster) to the image "pull" options, as in: 

```
    dock : {
      options : {
        auth : {},
        registry : {},
        docker : {},
        images : {
         test : {
            dockerfile : "...",
            options : {
              pull : {
                dockerNodes : [192.1.1.1, 192.1.1.2]
              }
            }
          }
        }
```

**Comment by JoTrdl** [comment]
Thanks to @lmoran, Pull/Push commands are supported now.
I updated the plugin on NPM: version 1.1.0

Thanks.
